spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=public
    username: postgres
    password: 321321
    driver-class-name: org.postgresql.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  map-underscore-to-camel-case: true

