
# 多数据源
spring:
  datasource:
        url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=public
        username: postgres
        password: 321321
        driver-class-name: org.postgresql.Driver
  mvc:
        static-path-pattern: /static/**
  reources:
       static-location: classpath:/static/
  velocity:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        enabled: true
        resource-loader-path: /templates
#        prefix: /templates/
        suffix: .vm



#  configuration:
#    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
##    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true






#
#
#logging:
#  level:
#    root: debug
#    com.autogen.code: info
