spring:
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:postgresql://10.254.130.27:5433/postgres
    username: gencode_dev
    password: Gencode_Dev
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
