spring:
  mvc:
    static-path-pattern: /**

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.254.130.27:5433/postgres
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://10.254.130.27:5433/postgres?currentSchema=autogencode
      username: gencode_dev
      password: Gencode_Dev




mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    root: debug
    com.autogen.code: info