
# 多数据源
spring:
  datasource:
    url: jdbc:postgresql://10.254.130.27:5433/postgres?currentSchema=public
    username: gencode_dev
    password: Gencode_Dev
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 3000
      idle-timeout: 60000
      max-lifetime: 300000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-column-label: true
    lazy-loading-enabled: false
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      table-underline: true
      update-strategy: ignored
  type-aliases-package: com.autogen.code.web.domain


#
#
#logging:
#  level:
#    root: debug
#    com.autogen.code: info
