
# 多数据源
spring:
  datasource:
        url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=public
        username: postgres
        password: 321321
        driver-class-name: org.postgresql.Driver
  mvc:
        static-path-pattern: /static/**
  reources:
       static-location: classpath:/static/

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#
#
#logging:
#  level:
#    root: debug
#    com.autogen.code: info
