/*
 Navicat Premium Data Transfer

 Source Server         : localPgSQL
 Source Server Type    : PostgreSQL
 Source Server Version : 140000
 Source Host           : localhost:5432
 Source Catalog        : postgres
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 140000
 File Encoding         : 65001

 Date: 03/12/2021 09:17:43
*/


-- ----------------------------
-- Sequence structure for TemplateDiy_templateId_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."TemplateDiy_templateId_seq";
CREATE SEQUENCE "public"."TemplateDiy_templateId_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;
ALTER SEQUENCE "public"."TemplateDiy_templateId_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for TemplateManage_templateId_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."TemplateManage_templateId_seq";
CREATE SEQUENCE "public"."TemplateManage_templateId_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;
ALTER SEQUENCE "public"."TemplateManage_templateId_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for templatediyup
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."templatediyup";
CREATE SEQUENCE "public"."templatediyup" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."templatediyup" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for templatemanageup
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."templatemanageup";
CREATE SEQUENCE "public"."templatemanageup" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."templatemanageup" OWNER TO "postgres";

-- ----------------------------
-- Table structure for Dependencies
-- ----------------------------
DROP TABLE IF EXISTS "public"."Dependencies";
CREATE TABLE "public"."Dependencies" (
  "id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "description" varchar(255) COLLATE "pg_catalog"."default",
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "group_name" varchar(255) COLLATE "pg_catalog"."default",
  "version_range" varchar(255) COLLATE "pg_catalog"."default",
  "reference" varchar(255) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."Dependencies" OWNER TO "postgres";

-- ----------------------------
-- Records of Dependencies
-- ----------------------------
BEGIN;
INSERT INTO "public"."Dependencies" VALUES ('codecentric-spring-boot-admin-client', 'Required for your application to register with a Codecentric''s Spring Boot Admin Server instance.', 'Codecentric''s Spring Boot Admin (Client)', 'Ops', '[2.0.0.RELEASE,2.6.0.M1)', 'https://codecentric.github.io/spring-boot-admin/current/#getting-started');
INSERT INTO "public"."Dependencies" VALUES ('cloud-starter-zookeeper-config', 'Enable and configure common patterns inside your application and build large distributed systems with Apache Zookeeper based components. The provided patterns include Service Discovery and Configuration.', 'Apache Zookeeper Configuration', 'Spring Cloud Config', NULL, 'https://docs.spring.io/spring-cloud-zookeeper/docs/current/reference/html/#distributed-configuration-usage');
INSERT INTO "public"."Dependencies" VALUES ('native', 'Incubating support for compiling Spring applications to native executables using the GraalVM native-image compiler.', 'Spring Native [Experimental]', 'Developer Tools', '[2.4.3.RELEASE,2.7.0.M1)', 'https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/');
INSERT INTO "public"."Dependencies" VALUES ('configuration-processor', 'Generate metadata for developers to offer contextual help and "code completion" when working with custom configuration keys (ex.application.properties/.yml files).', 'Spring Configuration Processor', 'Developer Tools', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#configuration-metadata-annotation-processor');
INSERT INTO "public"."Dependencies" VALUES ('h2', 'Provides a fast in-memory database that supports JDBC API and R2DBC access, with a small (2mb) footprint. Supports embedded and server modes as well as a browser based console application.', 'H2 Database', 'SQL', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('data-redis', 'Advanced and thread-safe Java Redis client for synchronous, asynchronous, and reactive usage. Supports Cluster, Sentinel, Pipelining, Auto-Reconnect, Codecs and much more.', 'Spring Data Redis (Access+Driver)', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-redis');
INSERT INTO "public"."Dependencies" VALUES ('webflux', 'Build reactive web applications with Spring WebFlux and Netty.', 'Spring Reactive Web', 'Web', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('data-rest', 'Exposing Spring Data repositories over REST via Spring Data REST.', 'Rest Repositories', 'Web', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#howto-use-exposing-spring-data-repositories-rest-endpoint');
INSERT INTO "public"."Dependencies" VALUES ('session', 'Provides an API and implementations for managing user session information.', 'Spring Session', 'Web', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('data-rest-explorer', 'Browsing Spring Data REST repositories in your browser.', 'Rest Repositories HAL Explorer', 'Web', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('hateoas', 'Eases the creation of RESTful APIs that follow the HATEOAS principle when working with Spring / Spring MVC.', 'Spring HATEOAS', 'Web', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-spring-hateoas');
INSERT INTO "public"."Dependencies" VALUES ('web-services', 'Facilitates contract-first SOAP development. Allows for the creation of flexible web services using one of the many ways to manipulate XML payloads.', 'Spring Web Services', 'Web', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-webservices');
INSERT INTO "public"."Dependencies" VALUES ('jersey', 'Framework for developing RESTful Web Services in Java that provides support for JAX-RS APIs.', 'Jersey', 'Web', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-jersey');
INSERT INTO "public"."Dependencies" VALUES ('vaadin', 'A web framework that allows you to write UI in pure Java without getting bogged down in JS, HTML, and CSS.', 'Vaadin', 'Web', '[2.0.0.RELEASE,2.6.0.M1)', 'https://vaadin.com/spring');
INSERT INTO "public"."Dependencies" VALUES ('thymeleaf', 'A modern server-side Java template engine for both web and standalone environments. Allows HTML to be correctly displayed in browsers and as static prototypes.', 'Thymeleaf', 'Template Engines', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-spring-mvc-template-engines');
INSERT INTO "public"."Dependencies" VALUES ('freemarker', 'Java library to generate text output (HTML web pages, e-mails, configuration files, source code, etc.) based on templates and changing data.', 'Apache Freemarker', 'Template Engines', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-spring-mvc-template-engines');
INSERT INTO "public"."Dependencies" VALUES ('mustache', 'Logic-less Templates. There are no if statements, else clauses, or for loops. Instead there are only tags.', 'Mustache', 'Template Engines', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-spring-mvc-template-engines');
INSERT INTO "public"."Dependencies" VALUES ('groovy-templates', 'Groovy templating engine.', 'Groovy Templates', 'Template Engines', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-spring-mvc-template-engines');
INSERT INTO "public"."Dependencies" VALUES ('security', 'Highly customizable authentication and access-control framework for Spring applications.', 'Spring Security', 'Security', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-security');
INSERT INTO "public"."Dependencies" VALUES ('oauth2-client', 'Spring Boot integration for Spring Security''s OAuth2/OpenID Connect client features.', 'OAuth2 Client', 'Security', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-security-oauth2-client');
INSERT INTO "public"."Dependencies" VALUES ('oauth2-resource-server', 'Spring Boot integration for Spring Security''s OAuth2 resource server features.', 'OAuth2 Resource Server', 'Security', '2.1.0.M2', 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-security-oauth2-server');
INSERT INTO "public"."Dependencies" VALUES ('data-ldap', 'Makes it easier to build Spring based applications that use the Lightweight Directory Access Protocol.', 'Spring LDAP', 'Security', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-ldap');
INSERT INTO "public"."Dependencies" VALUES ('okta', 'Okta specific configuration for Spring Security/Spring Boot OAuth2 features. Enable your Spring Boot application to work with Okta via OAuth 2.0/OIDC.', 'Okta', 'Security', '[2.1.2.RELEASE,2.6.0.M1)', 'https://github.com/okta/okta-spring-boot#readme');
INSERT INTO "public"."Dependencies" VALUES ('jdbc', 'Database Connectivity API that defines how a client may connect and query a database.', 'JDBC API', 'SQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-sql');
INSERT INTO "public"."Dependencies" VALUES ('data-jpa', 'Persist data in SQL stores with Java Persistence API using Spring Data and Hibernate.', 'Spring Data JPA', 'SQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-jpa-and-spring-data');
INSERT INTO "public"."Dependencies" VALUES ('data-jdbc', 'Persist data in SQL stores with plain JDBC using Spring Data.', 'Spring Data JDBC', 'SQL', NULL, 'https://docs.spring.io/spring-data/jdbc/docs/current/reference/html/');
INSERT INTO "public"."Dependencies" VALUES ('data-r2dbc', 'Provides Reactive Relational Database Connectivity to persist data in SQL stores using Spring Data in reactive applications.', 'Spring Data R2DBC', 'SQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/html/spring-boot-features.html#boot-features-r2dbc');
INSERT INTO "public"."Dependencies" VALUES ('mybatis', 'Persistence framework with support for custom SQL, stored procedures and advanced mappings. MyBatis couples objects with stored procedures or SQL statements using a XML descriptor or annotations.', 'MyBatis Framework', 'SQL', '[2.0.0.RELEASE,2.6.0.M1)', 'https://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/');
INSERT INTO "public"."Dependencies" VALUES ('liquibase', 'Liquibase database migration and source control library.', 'Liquibase Migration', 'SQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#howto-execute-liquibase-database-migrations-on-startup');
INSERT INTO "public"."Dependencies" VALUES ('flyway', 'Version control for your database so you can migrate from any version (incl. an empty database) to the latest version of the schema.', 'Flyway Migration', 'SQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#howto-execute-flyway-database-migrations-on-startup');
INSERT INTO "public"."Dependencies" VALUES ('jooq', 'Generate Java code from your database and build type safe SQL queries through a fluent API.', 'JOOQ Access Layer', 'SQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-jooq');
INSERT INTO "public"."Dependencies" VALUES ('db2', 'A JDBC driver that provides access to IBM DB2.', 'IBM DB2 Driver', 'SQL', '2.2.0.M6', NULL);
INSERT INTO "public"."Dependencies" VALUES ('derby', 'An open source relational database implemented entirely in Java.', 'Apache Derby Database', 'SQL', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('devtools', 'Provides fast application restarts, LiveReload, and configurations for enhanced development experience.', 'Spring Boot DevTools', 'Developer Tools', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#using-boot-devtools');
INSERT INTO "public"."Dependencies" VALUES ('lombok', 'Java annotation library which helps to reduce boilerplate code.', 'Lombok', 'Developer Tools', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('web', 'Build web, including RESTful, applications using Spring MVC. Uses Apache Tomcat as the default embedded container.', 'Spring Web', 'Web', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-developing-web-applications');
INSERT INTO "public"."Dependencies" VALUES ('mysql', 'MySQL JDBC and R2DBC driver.', 'MySQL Driver', 'SQL', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('oracle', 'A JDBC driver that provides access to Oracle.', 'Oracle Driver', 'SQL', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('postgresql', 'A JDBC and R2DBC driver that allows Java programs to connect to a PostgreSQL database using standard, database independent Java code.', 'PostgreSQL Driver', 'SQL', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('data-redis-reactive', 'Access Redis key-value data stores in a reactive fashion with Spring Data Redis.', 'Spring Data Reactive Redis', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-redis');
INSERT INTO "public"."Dependencies" VALUES ('data-mongodb', 'Store data in flexible, JSON-like documents, meaning fields can vary from document to document and data structure can be changed over time.', 'Spring Data MongoDB', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-mongodb');
INSERT INTO "public"."Dependencies" VALUES ('data-mongodb-reactive', 'Provides asynchronous stream processing with non-blocking back pressure for MongoDB.', 'Spring Data Reactive MongoDB', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-mongodb');
INSERT INTO "public"."Dependencies" VALUES ('data-elasticsearch', 'A distributed, RESTful search and analytics engine with Spring Data Elasticsearch.', 'Spring Data Elasticsearch (Access+Driver)', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-elasticsearch');
INSERT INTO "public"."Dependencies" VALUES ('data-cassandra', 'A free and open-source, distributed, NoSQL database management system that offers high-scalability and high-performance.', 'Spring Data for Apache Cassandra', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-cassandra');
INSERT INTO "public"."Dependencies" VALUES ('data-cassandra-reactive', 'Access Cassandra NoSQL Database in a reactive fashion.', 'Spring Data Reactive for Apache Cassandra', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-cassandra');
INSERT INTO "public"."Dependencies" VALUES ('geode', 'Apache Geode is a data management platform that helps users build real-time, highly concurrent, highly performant and reliable Spring Boot applications at scale that is compatible with Pivotal Cloud Cache.', 'Spring for Apache Geode', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/');
INSERT INTO "public"."Dependencies" VALUES ('data-couchbase', 'NoSQL document-oriented database that offers in memory-first architecture, geo-distributed deployments, and workload isolation.', 'Spring Data Couchbase', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-couchbase');
INSERT INTO "public"."Dependencies" VALUES ('data-couchbase-reactive', 'Access Couchbase NoSQL database in a reactive fashion with Spring Data Couchbase.', 'Spring Data Reactive Couchbase', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-couchbase');
INSERT INTO "public"."Dependencies" VALUES ('data-neo4j', 'An open source NoSQL database that stores data structured as graphs consisting of nodes, connected by relationships.', 'Spring Data Neo4j', 'NoSQL', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-neo4j');
INSERT INTO "public"."Dependencies" VALUES ('integration', 'Adds support for Enterprise Integration Patterns. Enables lightweight messaging and supports integration with external systems via declarative adapters.', 'Spring Integration', 'Messaging', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-integration');
INSERT INTO "public"."Dependencies" VALUES ('amqp', 'Gives your applications a common platform to send and receive messages, and your messages a safe place to live until received.', 'Spring for RabbitMQ', 'Messaging', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-amqp');
INSERT INTO "public"."Dependencies" VALUES ('kafka', 'Publish, subscribe, store, and process streams of records.', 'Spring for Apache Kafka', 'Messaging', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-kafka');
INSERT INTO "public"."Dependencies" VALUES ('kafka-streams', 'Building stream processing applications with Apache Kafka Streams.', 'Spring for Apache Kafka Streams', 'Messaging', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('activemq', 'Spring JMS support with Apache ActiveMQ ''Classic''.', 'Spring for Apache ActiveMQ 5', 'Messaging', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-activemq');
INSERT INTO "public"."Dependencies" VALUES ('artemis', 'Spring JMS support with Apache ActiveMQ Artemis.', 'Spring for Apache ActiveMQ Artemis', 'Messaging', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-artemis');
INSERT INTO "public"."Dependencies" VALUES ('websocket', 'Build WebSocket applications with SockJS and STOMP.', 'WebSocket', 'Messaging', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-websockets');
INSERT INTO "public"."Dependencies" VALUES ('rsocket', 'RSocket.io applications with Spring Messaging and Netty.', 'RSocket', 'Messaging', '2.2.0.M2', NULL);
INSERT INTO "public"."Dependencies" VALUES ('camel', 'Apache Camel is an open source integration framework that empowers you to quickly and easily integrate various systems consuming or producing data.', 'Apache Camel', 'Messaging', '[2.0.0.M1,2.6.0.M1)', NULL);
INSERT INTO "public"."Dependencies" VALUES ('solace', 'Connect to a Solace PubSub+ Advanced Event Broker to publish, subscribe, request/reply and store/replay messages', 'Solace PubSub+', 'Messaging', '[2.2.0.RELEASE,2.6.0.M1)', NULL);
INSERT INTO "public"."Dependencies" VALUES ('batch', 'Batch applications with transactions, retry/skip and chunk based processing.', 'Spring Batch', 'I/O', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#howto-batch-applications');
INSERT INTO "public"."Dependencies" VALUES ('validation', 'Bean Validation with Hibernate validator.', 'Validation', 'I/O', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-validation');
INSERT INTO "public"."Dependencies" VALUES ('mail', 'Send email using Java Mail and Spring Framework''s JavaMailSender.', 'Java Mail Sender', 'I/O', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-email');
INSERT INTO "public"."Dependencies" VALUES ('quartz', 'Schedule jobs using Quartz.', 'Quartz Scheduler', 'I/O', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('cache', 'Provides cache-related operations, such as the ability to update the content of the cache, but does not provide the actual data store.', 'Spring cache abstraction', 'I/O', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-caching');
INSERT INTO "public"."Dependencies" VALUES ('picocli', 'Build command line applications with picocli.', 'Picocli', 'I/O', '[2.4.0.RELEASE,2.6.0.BUILD-SNAPSHOT)', 'https://picocli.info/#_spring_boot_example');
INSERT INTO "public"."Dependencies" VALUES ('actuator', 'Supports built in (or custom) endpoints that let you monitor and manage your application - such as application health, metrics, sessions, etc.', 'Spring Boot Actuator', 'Ops', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#production-ready');
INSERT INTO "public"."Dependencies" VALUES ('hsql', 'Lightweight 100% Java SQL Database Engine.', 'HyperSQL Database', 'SQL', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('mariadb', 'MariaDB JDBC and R2DBC driver.', 'MariaDB Driver', 'SQL', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('sqlserver', 'A JDBC and R2DBC driver that provides access to Microsoft SQL Server and Azure SQL Database from any Java application.', 'MS SQL Server Driver', 'SQL', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('graphite', 'Publish Micrometer metrics to Graphite, a hierarchical metrics system backed by a fixed-size database.', 'Graphite', 'Observability', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/html/production-ready-features.html#production-ready-metrics-export-graphite');
INSERT INTO "public"."Dependencies" VALUES ('new-relic', 'Publish Micrometer metrics to New Relic, a SaaS offering with a full UI and a query language called NRQL.', 'New Relic', 'Observability', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/html/production-ready-features.html#production-ready-metrics-export-new-relic');
INSERT INTO "public"."Dependencies" VALUES ('prometheus', 'Expose Micrometer metrics in Prometheus format, an in-memory dimensional time series database with a simple built-in UI, a custom query language, and math operations.', 'Prometheus', 'Observability', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/html/production-ready-features.html#production-ready-metrics-export-prometheus');
INSERT INTO "public"."Dependencies" VALUES ('cloud-starter-sleuth', 'Distributed tracing via logs with Spring Cloud Sleuth.', 'Sleuth', 'Observability', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('wavefront', 'Publish Micrometer metrics to Tanzu Observability by Wavefront, a SaaS-based metrics monitoring and analytics platform that lets you visualize, query, and alert over data from across your entire stack.', 'Wavefront', 'Observability', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('cloud-starter-zipkin', 'Distributed tracing with an existing Zipkin installation and Spring Cloud Sleuth Zipkin.', 'Zipkin Client', 'Observability', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('restdocs', 'Document RESTful services by combining hand-written with Asciidoctor and auto-generated snippets produced with Spring MVC Test.', 'Spring REST Docs', 'Testing', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('testcontainers', 'Provide lightweight, throwaway instances of common databases, Selenium web browsers, or anything else that can run in a Docker container.', 'Testcontainers', 'Testing', NULL, 'https://www.testcontainers.org/');
INSERT INTO "public"."Dependencies" VALUES ('cloud-contract-verifier', 'Moves TDD to the level of software architecture by enabling Consumer Driven Contract (CDC) development.', 'Contract Verifier', 'Testing', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('cloud-contract-stub-runner', 'Stub Runner for HTTP/Messaging based communication. Allows creating WireMock stubs from RestDocs tests.', 'Contract Stub Runner', 'Testing', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('unboundid-ldap', 'Provides a platform neutral way for running a LDAP server in unit tests.', 'Embedded LDAP Server', 'Testing', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/html/boot-features-nosql.html#boot-features-ldap-embedded');
INSERT INTO "public"."Dependencies" VALUES ('flapdoodle-mongo', 'Provides a platform neutral way for running MongoDB in unit tests.', 'Embedded MongoDB Database', 'Testing', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('cloud-starter', 'Non-specific Spring Cloud features, unrelated to external libraries or integrations (e.g. Bootstrap context and @RefreshScope).', 'Cloud Bootstrap', 'Spring Cloud', NULL, 'https://spring.io/projects/spring-cloud-commons');
INSERT INTO "public"."Dependencies" VALUES ('cloud-function', 'Promotes the implementation of business logic via functions and supports a uniform programming model across serverless providers, as well as the ability to run standalone (locally or in a PaaS).', 'Function', 'Spring Cloud', NULL, 'https://cloud.spring.io/spring-cloud-function/');
INSERT INTO "public"."Dependencies" VALUES ('cloud-task', 'Allows a user to develop and run short lived microservices using Spring Cloud. Run them locally, in the cloud, and on Spring Cloud Data Flow.', 'Task', 'Spring Cloud', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('open-service-broker', 'Framework for building Spring Boot apps that implement the Open Service Broker API, which can deliver services to applications running within cloud native platforms such as Cloud Foundry, Kubernetes and OpenShift.', 'Open Service Broker', 'Spring Cloud Tools', '[2.0.0.RELEASE,2.5.0.M1)', 'https://docs.spring.io/spring-cloud-open-service-broker/docs/current/reference/');
INSERT INTO "public"."Dependencies" VALUES ('cloud-config-client', 'Client that connects to a Spring Cloud Config Server to fetch the application''s configuration.', 'Config Client', 'Spring Cloud Config', NULL, 'https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_client_side_usage');
INSERT INTO "public"."Dependencies" VALUES ('cloud-config-server', 'Central management for configuration via Git, SVN, or HashiCorp Vault.', 'Config Server', 'Spring Cloud Config', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('cloud-starter-vault-config', 'Provides client-side support for externalized configuration in a distributed system. Using HashiCorp''s Vault you have a central place to manage external secret properties for applications across all environments.', 'Vault Configuration', 'Spring Cloud Config', NULL, 'https://docs.spring.io/spring-cloud-vault/docs/current/reference/html/#client-side-usage');
INSERT INTO "public"."Dependencies" VALUES ('cloud-starter-consul-config', 'Enable and configure the common patterns inside your application and build large distributed systems with Hashicorp’s Consul. The patterns provided include Service Discovery, Distributed Configuration and Control Bus.', 'Consul Configuration', 'Spring Cloud Config', NULL, 'https://docs.spring.io/spring-cloud-consul/docs/current/reference/html/#distributed-configuration-usage');
INSERT INTO "public"."Dependencies" VALUES ('cloud-eureka', 'A REST based service for locating services for the purpose of load balancing and failover of middle-tier servers.', 'Eureka Discovery Client', 'Spring Cloud Discovery', NULL, 'https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/#service-discovery-eureka-clients');
INSERT INTO "public"."Dependencies" VALUES ('cloud-eureka-server', 'spring-cloud-netflix Eureka Server.', 'Eureka Server', 'Spring Cloud Discovery', NULL, 'https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/#spring-cloud-eureka-server');
INSERT INTO "public"."Dependencies" VALUES ('cloud-starter-zookeeper-discovery', 'Service discovery with Apache Zookeeper.', 'Apache Zookeeper Discovery', 'Spring Cloud Discovery', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('cloud-cloudfoundry-discovery', 'Service discovery with Cloud Foundry.', 'Cloud Foundry Discovery', 'Spring Cloud Discovery', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('cloud-starter-consul-discovery', 'Service discovery with Hashicorp Consul.', 'Consul Discovery', 'Spring Cloud Discovery', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('codecentric-spring-boot-admin-server', 'A community project to manage and monitor your Spring Boot applications. Provides a UI on top of the Spring Boot Actuator endpoints.', 'Codecentric''s Spring Boot Admin (Server)', 'Ops', '[2.0.0.RELEASE,2.6.0.M1)', 'https://codecentric.github.io/spring-boot-admin/current/#getting-started');
INSERT INTO "public"."Dependencies" VALUES ('datadog', 'Publish Micrometer metrics to Datadog, a dimensional time-series SaaS with built-in dashboarding and alerting.', 'Datadog', 'Observability', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/html/production-ready-features.html#production-ready-metrics-export-datadog');
INSERT INTO "public"."Dependencies" VALUES ('influx', 'Publish Micrometer metrics to InfluxDB, a dimensional time-series server that support real-time stream processing of data.', 'Influx', 'Observability', NULL, 'https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/html/production-ready-features.html#production-ready-metrics-export-influx');
INSERT INTO "public"."Dependencies" VALUES ('azure-cosmos-db', 'Fully managed NoSQL database service for modern app development, including Spring Data support.', 'Azure Cosmos DB', 'Microsoft Azure', '[2.2.11.RELEASE,2.6.0.M1)', 'https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db');
INSERT INTO "public"."Dependencies" VALUES ('azure-keyvault-secrets', 'Manage application secrets.', 'Azure Key Vault', 'Microsoft Azure', '[2.2.11.RELEASE,2.6.0.M1)', 'https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-keyvault-secrets');
INSERT INTO "public"."Dependencies" VALUES ('azure-storage', 'Azure Storage service integration.', 'Azure Storage', 'Microsoft Azure', '[2.2.11.RELEASE,2.6.0.M1)', 'https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-storage');
INSERT INTO "public"."Dependencies" VALUES ('cloud-gateway', 'Provides a simple, yet effective way to route to APIs and provide cross cutting concerns to them such as security, monitoring/metrics, and resiliency.', 'Gateway', 'Spring Cloud Routing', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('cloud-feign', 'Declarative REST Client. OpenFeign creates a dynamic implementation of an interface decorated with JAX-RS or Spring MVC annotations.', 'OpenFeign', 'Spring Cloud Routing', NULL, 'https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/');
INSERT INTO "public"."Dependencies" VALUES ('cloud-loadbalancer', 'Client-side load-balancing with Spring Cloud LoadBalancer.', 'Cloud LoadBalancer', 'Spring Cloud Routing', NULL, 'https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#spring-cloud-loadbalancer');
INSERT INTO "public"."Dependencies" VALUES ('cloud-resilience4j', 'Spring Cloud Circuit breaker with Resilience4j as the underlying implementation.', 'Resilience4J', 'Spring Cloud Circuit Breaker', NULL, 'https://cloud.spring.io/spring-cloud-static/spring-cloud-circuitbreaker/current/reference/html');
INSERT INTO "public"."Dependencies" VALUES ('cloud-gcp', 'Contains auto-configuration support for every Spring Cloud GCP integration. Most of the auto-configuration code is only enabled if other dependencies are added to the classpath.', 'GCP Support', 'Google Cloud Platform', '[2.0.0.RELEASE,2.6.0.M1)', 'https://cloud.spring.io/spring-cloud-gcp/reference/html/');
INSERT INTO "public"."Dependencies" VALUES ('cloud-gcp-pubsub', 'Adds the GCP Support entry and all the required dependencies so that the Google Cloud Pub/Sub integration work out of the box.', 'GCP Messaging', 'Google Cloud Platform', '[2.0.0.RELEASE,2.6.0.M1)', 'https://cloud.spring.io/spring-cloud-gcp/reference/html/#spring-integration');
INSERT INTO "public"."Dependencies" VALUES ('cloud-gcp-storage', 'Adds the GCP Support entry and all the required dependencies so that the Google Cloud Storage integration work out of the box.', 'GCP Storage', 'Google Cloud Platform', '[2.0.0.RELEASE,2.6.0.M1)', 'https://cloud.spring.io/spring-cloud-gcp/reference/html/#spring-resources');
INSERT INTO "public"."Dependencies" VALUES ('cloud-bus', 'Links nodes of a distributed system with a lightweight message broker which can used to broadcast state changes or other management instructions (requires a binder, e.g. Apache Kafka or RabbitMQ).', 'Cloud Bus', 'Spring Cloud Messaging', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('cloud-stream', 'Framework for building highly scalable event-driven microservices connected with shared messaging systems (requires a binder, e.g. Apache Kafka, RabbitMQ or Solace PubSub+).', 'Cloud Stream', 'Spring Cloud Messaging', NULL, NULL);
INSERT INTO "public"."Dependencies" VALUES ('scs-config-client', 'Config client on VMware Tanzu Application Service.', 'Config Client (TAS)', 'VMware Tanzu Application Service', '[2.0.0.RELEASE,2.6.0.M1)', 'https://docs.pivotal.io/spring-cloud-services/');
INSERT INTO "public"."Dependencies" VALUES ('scs-service-registry', 'Eureka service discovery client on VMware Tanzu Application Service.', 'Service Registry (TAS)', 'VMware Tanzu Application Service', '[2.0.0.RELEASE,2.6.0.M1)', 'https://docs.pivotal.io/spring-cloud-services/');
INSERT INTO "public"."Dependencies" VALUES ('scs-circuit-breaker', 'Hystrix circuit breaker client on VMware Tanzu Application Service.', 'Circuit Breaker (TAS)', 'VMware Tanzu Application Service', '[2.0.0.RELEASE,2.5.0.M1)', 'https://docs.pivotal.io/spring-cloud-services/');
INSERT INTO "public"."Dependencies" VALUES ('azure-support', 'Auto-configuration for Azure Services (Service Bus, Storage, Active Directory, Key Vault, and more).', 'Azure Support', 'Microsoft Azure', '[2.2.11.RELEASE,2.6.0.M1)', 'https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring');
INSERT INTO "public"."Dependencies" VALUES ('azure-active-directory', 'Spring Security integration with Azure Active Directory for authentication.', 'Azure Active Directory', 'Microsoft Azure', '[2.2.11.RELEASE,2.6.0.M1)', 'https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory');
COMMIT;

-- ----------------------------
-- Table structure for TemplateDiy
-- ----------------------------
DROP TABLE IF EXISTS "public"."TemplateDiy";
CREATE TABLE "public"."TemplateDiy" (
  "template_id" int4 NOT NULL DEFAULT nextval('templatediyup'::regclass),
  "template_name" char(255) COLLATE "pg_catalog"."default",
  "template_type" char(255) COLLATE "pg_catalog"."default",
  "template_content" text COLLATE "pg_catalog"."default",
  "package_name" char(255) COLLATE "pg_catalog"."default",
  "path" char(255) COLLATE "pg_catalog"."default",
  "extension_name" char(255) COLLATE "pg_catalog"."default",
  "prefix_default" char(255) COLLATE "pg_catalog"."default",
  "create_time" char(255) COLLATE "pg_catalog"."default",
  "author" char(255) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."TemplateDiy" OWNER TO "postgres";

-- ----------------------------
-- Records of TemplateDiy
-- ----------------------------
BEGIN;
INSERT INTO "public"."TemplateDiy" VALUES (8, 'mapper-mybatis                                                                                                                                                                                                                                                 ', 'java                                                                                                                                                                                                                                                           ', NULL, '                                                                                                                                                                                                                                                               ', 'mapper/                                                                                                                                                                                                                                                        ', 'java                                                                                                                                                                                                                                                           ', '/src/mian/java/                                                                                                                                                                                                                                                ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
INSERT INTO "public"."TemplateDiy" VALUES (9, 'mapper-mybatisPlus                                                                                                                                                                                                                                             ', 'java                                                                                                                                                                                                                                                           ', NULL, '                                                                                                                                                                                                                                                               ', 'mapper/                                                                                                                                                                                                                                                        ', 'java                                                                                                                                                                                                                                                           ', '/src/mian/java/                                                                                                                                                                                                                                                ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
INSERT INTO "public"."TemplateDiy" VALUES (4, 'service-impl-mybatis                                                                                                                                                                                                                                           ', 'java                                                                                                                                                                                                                                                           ', NULL, '                                                                                                                                                                                                                                                               ', 'service/impl                                                                                                                                                                                                                                                   ', 'java                                                                                                                                                                                                                                                           ', '/src/mian/java/                                                                                                                                                                                                                                                ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
INSERT INTO "public"."TemplateDiy" VALUES (3, 'service-interface-mybatisPlus                                                                                                                                                                                                                                  ', 'java                                                                                                                                                                                                                                                           ', NULL, '                                                                                                                                                                                                                                                               ', 'service/                                                                                                                                                                                                                                                       ', 'java                                                                                                                                                                                                                                                           ', '/src/mian/java/                                                                                                                                                                                                                                                ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
INSERT INTO "public"."TemplateDiy" VALUES (6, 'domain-mybatis                                                                                                                                                                                                                                                 ', 'java                                                                                                                                                                                                                                                           ', NULL, '                                                                                                                                                                                                                                                               ', 'domain/                                                                                                                                                                                                                                                        ', 'java                                                                                                                                                                                                                                                           ', '/src/mian/java/                                                                                                                                                                                                                                                ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
INSERT INTO "public"."TemplateDiy" VALUES (7, 'domain-mybatisPlus                                                                                                                                                                                                                                             ', 'java                                                                                                                                                                                                                                                           ', NULL, '                                                                                                                                                                                                                                                               ', 'domain/                                                                                                                                                                                                                                                        ', 'java                                                                                                                                                                                                                                                           ', '/src/mian/java/                                                                                                                                                                                                                                                ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
INSERT INTO "public"."TemplateDiy" VALUES (1, 'controller                                                                                                                                                                                                                                                     ', 'java                                                                                                                                                                                                                                                           ', NULL, '                                                                                                                                                                                                                                                               ', 'web/controller/                                                                                                                                                                                                                                                ', 'java                                                                                                                                                                                                                                                           ', '/src/mian/java/                                                                                                                                                                                                                                                ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
INSERT INTO "public"."TemplateDiy" VALUES (2, 'service-interface-mybatis                                                                                                                                                                                                                                      ', 'java                                                                                                                                                                                                                                                           ', NULL, '                                                                                                                                                                                                                                                               ', 'service/                                                                                                                                                                                                                                                       ', 'java                                                                                                                                                                                                                                                           ', '/src/mian/java/                                                                                                                                                                                                                                                ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
INSERT INTO "public"."TemplateDiy" VALUES (11, 'application.yml.vm                                                                                                                                                                                                                                                ', 'yml                                                                                                                                                                                                                                                            ', NULL, '                                                                                                                                                                                                                                                               ', '                                                                                                                                                                                                                                                               ', 'yml                                                                                                                                                                                                                                                            ', '/src/main/resources                                                                                                                                                                                                                                            ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
INSERT INTO "public"."TemplateDiy" VALUES (10, 'maper.xml                                                                                                                                                                                                                                                      ', 'xml                                                                                                                                                                                                                                                            ', NULL, '                                                                                                                                                                                                                                                               ', 'mapper/                                                                                                                                                                                                                                                        ', 'xml                                                                                                                                                                                                                                                            ', '/src/main/resources                                                                                                                                                                                                                                            ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
INSERT INTO "public"."TemplateDiy" VALUES (5, 'service-impl-mabatisPlus                                                                                                                                                                                                                                       ', 'java                                                                                                                                                                                                                                                           ', NULL, '                                                                                                                                                                                                                                                               ', 'service/impl                                                                                                                                                                                                                                                   ', 'java                                                                                                                                                                                                                                                           ', '/src/mian/java/                                                                                                                                                                                                                                                ', '2021/12/2                                                                                                                                                                                                                                                      ', 'JiaGuo                                                                                                                                                                                                                                                         ');
COMMIT;

-- ----------------------------
-- Table structure for TemplateManage
-- ----------------------------
DROP TABLE IF EXISTS "public"."TemplateManage";
CREATE TABLE "public"."TemplateManage" (
  "class_name" char(255) COLLATE "pg_catalog"."default",
  "package_name" char(255) COLLATE "pg_catalog"."default",
  "table_name" char(255) COLLATE "pg_catalog"."default",
  "template_content" char(255) COLLATE "pg_catalog"."default",
  "template_id" int4 NOT NULL DEFAULT nextval('templatemanageup'::regclass),
  "del_mark" bool,
  "create_time" char(255) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."TemplateManage" OWNER TO "postgres";

-- ----------------------------
-- Records of TemplateManage
-- ----------------------------
BEGIN;
INSERT INTO "public"."TemplateManage" VALUES ('1                                                                                                                                                                                                                                                              ', '1                                                                                                                                                                                                                                                              ', '1                                                                                                                                                                                                                                                              ', '1                                                                                                                                                                                                                                                              ', 1, 'f', '1                                                                                                                                                                                                                                                              ');
INSERT INTO "public"."TemplateManage" VALUES ('2                                                                                                                                                                                                                                                              ', '2                                                                                                                                                                                                                                                              ', '2                                                                                                                                                                                                                                                              ', '2                                                                                                                                                                                                                                                              ', 2, 'f', '2                                                                                                                                                                                                                                                              ');
INSERT INTO "public"."TemplateManage" VALUES ('22                                                                                                                                                                                                                                                             ', '22                                                                                                                                                                                                                                                             ', '22                                                                                                                                                                                                                                                             ', '22                                                                                                                                                                                                                                                             ', 3, 'f', '22                                                                                                                                                                                                                                                             ');
INSERT INTO "public"."TemplateManage" VALUES ('22                                                                                                                                                                                                                                                             ', '22                                                                                                                                                                                                                                                             ', '22                                                                                                                                                                                                                                                             ', '22                                                                                                                                                                                                                                                             ', 4, 'f', '22                                                                                                                                                                                                                                                             ');
INSERT INTO "public"."TemplateManage" VALUES ('class3                                                                                                                                                                                                                                                         ', 'pack3                                                                                                                                                                                                                                                          ', 'table3                                                                                                                                                                                                                                                         ', 'temp3                                                                                                                                                                                                                                                          ', 6, 'f', '03-11-2021 10:28:26                                                                                                                                                                                                                                            ');
INSERT INTO "public"."TemplateManage" VALUES ('#{className11}                                                                                                                                                                                                                                                 ', '#{packageName11}                                                                                                                                                                                                                                               ', '#{tableName11}                                                                                                                                                                                                                                                 ', '#{templateContent11}                                                                                                                                                                                                                                           ', 5, 't', '#{createTime11}                                                                                                                                                                                                                                                ');
INSERT INTO "public"."TemplateManage" VALUES ('1111                                                                                                                                                                                                                                                           ', '1111                                                                                                                                                                                                                                                           ', '1111                                                                                                                                                                                                                                                           ', '1111                                                                                                                                                                                                                                                           ', 8, 't', '55555                                                                                                                                                                                                                                                          ');
COMMIT;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."TemplateDiy_templateId_seq"
OWNED BY "public"."TemplateDiy"."template_id";
SELECT setval('"public"."TemplateDiy_templateId_seq"', 5, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."TemplateManage_templateId_seq"
OWNED BY "public"."TemplateManage"."template_id";
SELECT setval('"public"."TemplateManage_templateId_seq"', 5, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."templatediyup"', 14, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."templatemanageup"', 11, true);

-- ----------------------------
-- Primary Key structure for table Dependencies
-- ----------------------------
ALTER TABLE "public"."Dependencies" ADD CONSTRAINT "dependencies_pk" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table TemplateDiy
-- ----------------------------
CREATE UNIQUE INDEX "templatediy_templateid_uindex" ON "public"."TemplateDiy" USING btree (
  "template_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table TemplateDiy
-- ----------------------------
ALTER TABLE "public"."TemplateDiy" ADD CONSTRAINT "TemplateDiy_pkey" PRIMARY KEY ("template_id");

-- ----------------------------
-- Primary Key structure for table TemplateManage
-- ----------------------------
ALTER TABLE "public"."TemplateManage" ADD CONSTRAINT "TemplateManage_pkey" PRIMARY KEY ("template_id");
