spring:
  mvc:
    static-path-pattern: /**
  datasource:
#    服务器
#    url: jdbc:postgresql://10.254.130.27:5433/postgres
#    username: gencode_dev
#    password: Gencode_Dev
#    driver-class-name: org.postgresql.Driver

#     本机
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 321321
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
